# FULL HOT BACKUP with optional controlfile and archivelogs
CONNECT TARGET /
RUN {
  CONFIGURE CONTROLFILE AUTOBACKUP ON;
  CROSSCHECK BACKUP;
  SQL 'ALTER SYSTEM ARCHIVE LOG CURRENT';
  BACKUP AS {COMPRESSION} BACKUPSET
    DATABASE
    {INCLUDE_ARCHIVE}
    FORMAT '{OUTPUT_DIR}/%d_full_%T_%U.bkp';
  {CONTROLFILE_BACKUP}
  REPORT OBSOLETE;
  DELETE NOPROMPT OBSOLETE;
}
