# INCREMENTAL LEVEL 1
CONNECT TARGET /
RUN {
  CONFIGURE CONTROLFILE AUTOBACKUP ON;
  BACKUP AS {COMPRESSION} INCREMENTAL LEVEL 1
    DATABASE
    {INCLUDE_ARCHIVE}
    FORMAT '{OUTPUT_DIR}/%d_lvl1_%T_%U.bkp';
  {CONTROLFILE_BACKUP}
  REPORT SCHEMA;
}
