# PARTIAL BACKUP: SELECTED TABLESPACES OR DATAFILES
CONNECT TARGET {RMAN_CONNECT}
RUN {
  CONFIGURE CONTROLFILE AUTOBACKUP ON;
  BACKUP AS {COMPRESSION} BACKUPSET
    {OBJECT_LIST}
    {INCLUDE_ARCHIVE}
    FORMAT '{OUTPUT_DIR}/%d_partial_%T_%U.bkp';
  {CONTROLFILE_BACKUP}
}
